language: php

# list any PHP version you want to test against
php:
  - 7.1

#指定分支，只有指定的分支提交时才会运行脚本
branches:
  only:
    - master

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction

script: phpunit -c phpunit.xml